apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: regain-access
spec:
  selector:
    matchLabels:
      app: regain-access
  template:
    metadata:
      labels:
        app: regain-access
    spec:
      initContainers:
      - name: setup-trusted-cert
        image: alpine
        command: ["/bin/sh", "-c", "apiclient set pki.my-trusted-bundle.data=\"$(CERT_DATA)\" pki.my-trusted-bundle.trusted=true"]
        volumeMounts:
        - mountPath: /usr/bin/apiclient
          name: apiclient
          readOnly: true
        - mountPath: /run/api.sock
          name: apiserver-socket
        securityContext:
          seLinuxOptions:
            level: s0
            role: system_r
            type: control_t
            user: system_u
      containers:
      - name: regain-access
        image: fedora
        command: ["/bin/sleep", "infinity"]  # Or any other command that does nothing and keeps the container running
        volumeMounts:
        - mountPath: /usr/bin/apiclient
          name: apiclient
          readOnly: true
        - mountPath: /run/api.sock
          name: apiserver-socket
        securityContext:
          seLinuxOptions:
            level: s0
            role: system_r
            type: control_t
            user: system_u
      volumes:
        - name: apiclient
          hostPath:
            path: /usr/bin/apiclient
            type: File
        - name: apiserver-socket
          hostPath:
            path: /run/api.sock
            type: Socket
